name: bot

on:
  schedule:
    - cron: "* */10 * * *" # every 30 minutes

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{secrets.LOGIN}}
      PASS: ${{secrets.PASS}}
      PAGE: ${{secrets.PAGE}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm start
