name: report

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      LOGIN: ${{LOGIN}}
      PASS: ${{PASS}}
      PAGE: ${{PAGE}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      with:
        node-version: "20"
      - run: npm install
      - run: npm start
