name: report

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{LOGIN}}
      PASS: ${{PASS}}
      PAGE: ${{PAGE}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
        node-version: '20'
      - run: npm install
      - run: npm start
